name: Check Format

on:
  pull_request:
    branches:
      - main

jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }} # Check out the branch that triggered the workflow

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Match with your project's required Node.js version

      - name: Install dependencies
        run: npm install

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1.2

      - name: Check if Dart files are formatted
        run: dart format --output=none --set-exit-if-changed .

      - name: Check if other files are formatted according to Prettier
        run: npx prettier --check .
