name: PR Build and Test

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  build-and-test-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk

  build-and-test-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter test
      - run: flutter build ios --no-codesign
